# Generated by Django 3.0.8 on 2020-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
